### ISSUE TITLE
Data from Hiera

### ISSUE THREAD

**Issue by ITD27M01** [mmckinst/puppet-hash2stuff#14]
Hi

I want to promote the ability to generate format data file (json/yaml/ini) from hiera data. Hiera can have any type of variables - Hash/Array and I think the module should intelligently handle such cases.

Currently only hashes are allowed:

```yaml
puppet_module::datavar:
   hashdata:
      arraydata:
        - firstthing
        - secondthing
```

But hiera can have arrays too:

```yaml
puppet_module::datavar:
    - firstthing:
       hashdata:
         firstthing: value
         secondthing: value
```

Possible solution is add check for Array type too:

```ruby
unless arguments[0].is_a?(Hash) || arguments[0].is_a?(Array)
   raise(Puppet::ParseError, 'hash2yaml(): requires a hash or array as argument')
end
```

https://github.com/mmckinst/puppet-hash2stuff/blob/3101e8e45a4b426d49fdf742c589f0e9e8ee7452/lib/puppet/parser/functions/hash2yaml.rb#L11
